## Import dependencies

In [1]:
import pandas as pd

## Load dataset

In [3]:
path = "products.csv"
df = pd.read_csv(path)
df.head()

,title,price_idr,rating,colors,sizes,gender,timestamp
0,T-shirt 2,1634400.0,5.0,3,M,women,2026-02-18 13:39:19.733525
1,Hoodie 3,7950080.0,5.0,3,L,unisex,2026-02-18 13:39:19.733949
2,Pants 4,7476960.0,5.0,3,XL,men,2026-02-18 13:39:19.734278
3,Outerwear 5,5145440.0,5.0,3,XXL,women,2026-02-18 13:39:19.734598
4,Jacket 6,2453920.0,5.0,3,S,unisex,2026-02-18 13:39:19.735066

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      867 non-null    object
 1   price_idr  867 non-null    float64
 2   rating     867 non-null    float64
 3   colors     867 non-null    int64
 4   sizes      867 non-null    object
 5   gender     867 non-null    object
 6   timestamp  867 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 47.5+ KB

In [9]:
df.describe(include='all')

,title,price_idr,rating,colors,sizes,gender,timestamp
count,867,8.670000e+02,867.0,867.0,867,867,867
unique,867,NaN,NaN,NaN,5,3,867
top,Pants 1000,NaN,NaN,NaN,M,women,2026-02-18 13:40:26.406885
freq,1,NaN,NaN,NaN,200,300,1
mean,NaN,4.804335e+06,5.0,3.0,NaN,NaN,NaN
std,NaN,2.299773e+06,0.0,0.0,NaN,NaN,NaN
min,NaN,8.056000e+05,5.0,3.0,NaN,NaN,NaN
25%,NaN,2.778560e+06,5.0,3.0,NaN,NaN,NaN
50%,NaN,4.776800e+06,5.0,3.0,NaN,NaN,NaN
75%,NaN,6.836240e+06,5.0,3.0,NaN,NaN,NaN
max,NaN,8.794880e+06,5.0,3.0,NaN,NaN,NaN

In [ ]:
from google.colab import drive
drive.mount('/content/drive')